# Change these first
owner: busupdev # Your GitHub organization or username, where this repository lives
repo: monitoring # The name of this repository

sites:
  - name: Business-Up
    url: https://business-up.org
    
  - name: MON CHER CAPRISE
    url: https://monchercaprise.ru
    
  - name: Скандинавский профиль
    url: https://scandicprofile.ru
    
  - name: ВСО Профиль [ Лендинг ]
    url: https://vso-profil.ru
    
  - name: ANFI
    url: https://anfiacademy.ru

  - name: AcademKids [ Основная сеть ]
    url: http://academkids.ru

  - name: AcademKids [ Франшиза ]
    url: https://franchise.academkids.ru
    
  - name: AcademKids [ Летние смены ]
    url: https://leto.academkids.ru

  - name: AcademKids [ Летние смены ]
    url: https://leto.academkids.ru

  - name: AcademKids [ Соляная комната ]
    url: https://saltroom.academkids.ru

  - name: AcademKids [ Личный кабинет ]
    url: https://lk.academkids.ru

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: busupdev.github.io/monitoring
  baseUrl: /monitoring
  name: Business UP | Панель мониторинга
  introTitle: "Мониторинг сайтов: защита вашего бизнеса от простоев"
  introMessage: Ваш сайт еще не в списке? Или его вообще нет? [Свяжитесь с нами.](https://t.me/Konstantin100)
